### PR TITLE
Unassign event role command now sets view state to single event 

### LINKED ISSUE #293: [PE-D][Tester C] unassignEventRole displays confusing member list
**Steps to Reproduce**
1. Assigning some members to an event 1, e.g. `assignEvent m/Alex Yeoh e/Movie Night r/OIC`, `assignEvent m/Bernice Yu e/Movie Night`
2. `listEvents` and then `event 1`
3. Now the UI is like this:

Image

4. After that, try `unassignEventRole m/Alex Yeoh e/Movie Night r/OIC` 

Image

This shows a filtered list, which users can directly use `deleteMember`. For example, use `deleteMember 1` and then `listMembers`.

Image
This can lead to accidental deletion, especially when it is not specified in the user guide.

**Expected**
Should be consistent with the UI after `assignEvent` or `unassignEvent`, which means either remaining in the previous view or displaying the event details

**Actual**
Show a filtered list containing the members assigned to the event. This can make the users feel confused, and also `deleteMember` can work too. This could lead to members accidentally deleting a member, thinking that this is the event roster view.  The User Guide also does not notify users about this member list.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`

### PR DESCRIPTION
**Pull request by JasonChang419**
closes #293

### CODE REVIEW

File: src/main/java/seedu/club/logic/commands/event/UnassignEventRoleCommand.java [hunk 1]
```diff
@@ -99,7 +99,7 @@ public CommandResult execute(Model model) throws CommandException {
         model.updateFilteredEventList(e -> e.equals(event));
         model.updateFilteredMemberList(m -> true);
         model.updateFilteredMemberList(m -> event.getRoster().contains(m));
```
Comment (hongxun03) [inline src/main/java/seedu/club/logic/commands/event/UnassignEventRoleCommand.java]: Im just wondering, if display single event, do we need these 3 lines?
```suggestion
```

**Review by hongxun03 — APPROVED** [review]
LGTM, but I left some comments regarding the deletion of some lines.
