### PR TITLE
Fix backslash not converting to forward slash bug

### LINKED ISSUE #358: Backslash not converting to forward slash for name and detail fields

### PR DESCRIPTION
**Pull request by rongkangw**
closes #358

### CODE REVIEW

File: src/main/java/seedu/club/model/event/Event.java [hunk 1]
```diff
@@ -73,6 +73,9 @@ public Event(Name name, DateTime from, DateTime to,
         // Starting date/time must be before ending date/time
         checkArgument(from.isBefore(to), MESSAGE_CONSTRAINTS_DATE);
         checkArgument(isValidDetails(detail), MESSAGE_CONSTRAINTS_DETAILS);
```
Comment (ferroklaser) [inline src/main/java/seedu/club/model/event/Event.java]: I think this line is supposed to be removed 
`checkArgument(isValidDetails(detail), MESSAGE_CONSTRAINTS_DETAILS);`
